# Generated by Django 2.1.11 on 2020-03-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0004_auto_20200319_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='fromTime',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='guest',
            name='toTime',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
