# Generated by Django 2.1.11 on 2020-03-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0005_auto_20200320_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='IsEmpty',
        ),
        migrations.AddField(
            model_name='guest',
            name='fromDate',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='guest',
            name='toDate',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='guest',
            name='fromTime',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='guest',
            name='toTime',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
