# Generated by Django 2.1.11 on 2020-03-21 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0008_auto_20200321_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='fromDate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
