# Generated by Django 2.1.11 on 2020-03-21 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0009_auto_20200321_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='fromDate',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='toDate',
        ),
        migrations.AddField(
            model_name='room',
            name='IsEmpty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='fromTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='guest',
            name='toTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
