# Generated by Django 2.1.11 on 2020-03-21 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0010_auto_20200321_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='IsEmpty',
        ),
        migrations.AddField(
            model_name='guest',
            name='fromDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='toDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='fromTime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='toTime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
