# Generated by Django 2.1.11 on 2020-03-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0011_auto_20200321_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='fromDate',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='toDate',
        ),
        migrations.AlterField(
            model_name='guest',
            name='fromTime',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='guest',
            name='toTime',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
