# Generated by Django 2.1.11 on 2020-03-21 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0012_auto_20200321_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='fromDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='guest',
            name='toDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='guest',
            name='fromTime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='toTime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
    ]
