# Generated by Django 2.1.11 on 2020-03-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0014_auto_20200321_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='Time',
            new_name='Choices',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='roomAllotted',
        ),
    ]
