# Generated by Django 2.1.11 on 2020-03-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0015_auto_20200321_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='Choices',
            new_name='Time',
        ),
        migrations.AddField(
            model_name='guest',
            name='roomAllotted',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RoomBooking.Room'),
        ),
    ]
