# Generated by Django 2.1.11 on 2020-03-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0016_auto_20200321_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='roomAllotted',
        ),
    ]
