# Generated by Django 2.1.11 on 2020-03-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0017_remove_guest_roomallotted'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='roomAllotted',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RoomBooking.Room'),
        ),
    ]
