# Generated by Django 2.1.11 on 2020-03-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0018_guest_roomallotted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='RoomNo',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='roomAllotted',
        ),
        migrations.AddField(
            model_name='available',
            name='roomNo',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='guest',
            name='roomNo',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
